---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    yum:
      name: "*"
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: install_elasticstack_centos
  become: true
  roles:
    - name: elastic_CentOS

- hosts: install_elasticstack_Ubuntu
  become: true
  roles:
    - name: elastic_Ubuntu
